config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'api'

urlpatterns = [
    path('', views.companies_view),
    path('employees/<int:com_pk>',views.employees_view,name='employees'),
    path('employee_add/',views.employees_add,name='employee_add')

]

main/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    comment = models.TextField()
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from main.models import Company,Employee
from django.db.models import Count
from django.http import HttpResponseRedirect

# Create your views here.


def companies_view(request):

    companies_with_employees = Company.objects.prefetch_related('employee_set')
    return render(request, 'companies.html', {"companies_with_employees":companies_with_employees })


def employees_view(request,com_pk):
    employees=Employee.objects.all()
    return render(request,'employees.html',{'employees':employees,'com_pk':com_pk})

def employees_add(request):
    if request.method == 'POST':
        try:
            emp_id = request.POST.get('employee')
            com_id = request.POST.get('company_id')
            employee = Employee.objects.get(pk=emp_id)
            company = Company.objects.get(pk=com_id)
        
        # Check if the employee is already linked to a company
            if employee.company:
                # Unlink the employee from their current company
                employee.company = None
                employee.save()
        
        # Link the employee to the new company
            employee.company = company
            employee.save()
            return HttpResponseRedirect('/')
        except:
            return HttpResponse('Please Select Company and Employee!! ')
    return HttpResponse('Please Select Company and Employee!! ')

templates/companies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Companies List</title>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 70%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
<table>
    <tr>
        <th style="width: 20%;">Company</th>
        <th>Employees</th>
    </tr>
    {% for company in companies_with_employees %}
    <tr>
        <td>{{ company.name }} <a href="{% url 'api:employees' company.id %}" >(Add Employee)</a></td>
        <td>
            {% for employee in company.employee_set.all %}
                {{employee.first_name}} {{employee.last_name}},
            {% endfor %}
                
        </td>
    </tr>
    {% endfor %}
</table>
</body>
</html>

templates/employees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee List</title>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <style>
        .select2{
            width: 50%;
        }
        .submit_button{
            margin-left:1rem;
            margin-top:1rem;
            width:5rem;
            padding:0.5rem;
            border-radius:0.25rem;
        }
    </style>
</head>
<body>
    <h1>Select an Employee</h1>
    <form action="{% url 'api:employee_add' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="company_id" value="{{ com_pk }}">
        <label for="employee">Choose an Employee:</label>
        <select id="employee" name="employee" class="select2">
            <option value='None'>None</option>
            {% for employee in employees %}
                <option value="{{ employee.id }}">{{ employee.first_name }} {{ employee.last_name }}</option>
            {% endfor %}
        </select>
        <br>
        <input type="submit" value="Select" class='submit_button'>
    </form>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
        $('.select2').select2();
        });
    </script>
</body>
</html>